name: Portfolio Server Deployment

on: [push, workflow_dispatch]

jobs:
    test-code:
        runs-on: ubuntu-latest
        steps:
            - name: Copy files to the server
              uses: actions/checkout@v6

            - name: Install Node Js
              uses: actions/setup-node@v5
              with:
                  node-version: "24.13.0"

            - name: Check Version
              run: node -v

            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npm test
